### PR TITLE
Fork figures package so it can be published for esm/cjs

### PR DESCRIPTION
**Pull request by jeffsee55**
Closes https://github.com/SBoudrias/Inquirer.js/issues/1386

This pr ports the `is-unicode-supported` and `figures` packages so they can be dual published in ESM/CJS.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Thanks! I pushed an extra update to also cover `inquirer`.

**Comment by jeffsee55** [comment]
Ok great! Wasn't sure about that one. Was about to write some tests to please codecov, they're pretty trivial though so let me know if it's worthwhile doing so.

**Comment by SBoudrias** [comment]
I'm fine ignoring the codecov. But if it's trivial, it does make it easier to manage when people send PRs.

**Comment by SBoudrias** [comment]
Uou can also ignore the linting job; it's because the package is not published, and to make the linting job faster it doesn't depends on building the package.

**Comment by SBoudrias** [comment]
I went ahead and push a release right now since I'm planning to get breaking change in today.

A follow-up PR with test would be great if you're still planning it.

Last point is debugging the eslint failure; since I was wrong 🤦🏻  https://github.com/SBoudrias/Inquirer.js/pull/1389

**Pull request merged**
