### PR TITLE
fix: Module '"node:readline"' has no default export.

### PR DESCRIPTION
**Pull request by saadfrhan**

### CODE REVIEW

**Comment by SBoudrias** [comment]
@saadfrhan where did you see this? Running under which environment? (and Node.js version?)

It's always been passing CI for Node 16, 18, and 20.

**Comment by saadfrhan** [comment]
GitHub Action link: https://github.com/saadfrhan/cli-nodejs-typescript-cli-template/actions/runs/5750427823/job/15587186738

Source code: https://github.com/saadfrhan/cli-nodejs-typescript-cli-template/tree/f3913f7989ae79a1522fd11cafdb54ca9d3f1747

I saw this error in the GitHub Action environment:
image

Node version: v16.20.1

**Comment by saadfrhan** [comment]
Tried with the latest LTS version as well, on the terminal.

image

**Comment by SBoudrias** [comment]
I think you need to add this line to your `tsconfig`:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  }
}
```

> To provide backwards compatibility, Node.js allows you to import most CommonJS packages with a default import. This flag tells TypeScript that it's okay to use import on CommonJS modules.

**Pull request closed without merging**
