### PR TITLE
upgrade to RxJS 5

### PR DESCRIPTION
**Pull request by user3587412**
Hello, this pull request upgrades RxJS to version 5

### CODE REVIEW

**Comment by SBoudrias** [comment]
I'm wondering, so there's no more rx lite?

**Comment by user3587412** [comment]
To my knowledge, no. However starting with RxJS 5 we can use [prototype patching](https://github.com/ReactiveX/rxjs/tree/e659f0cf060f9106ab9af0a9137eb78c99ad6197#installation-and-usage) to import just the operators we need. They've also recently added [lettable operators](https://github.com/ReactiveX/rxjs/blob/e659f0cf060f9106ab9af0a9137eb78c99ad6197/doc/lettable-operators.md) as an alternative.

**Comment by SBoudrias** [comment]
Thanks for your answer. I'll merge this branch, but not right now as I just released a major version. I want to make sure this release is stable before pushing a new one out.

**Comment by kbrandwijk** [comment]
Any plans for releasing this?

**Comment by SBoudrias** [comment]
@kbrandwijk are you waiting for this for new features?

**Comment by kbrandwijk** [comment]
I'm looking to get started with it, and I want to plan it a bit, so if I start now, I won't be confronted with an upgrade to v5 in two weeks 😄

**Comment by SBoudrias** [comment]
I'll cut a release later today :)

**Comment by soruly** [comment]
moving to RxJS 5 adds 3000+ more files in node_modules
RxJS put all their source code and source map in production node_modules
https://github.com/ReactiveX/rxjs/issues/3334

I'd refrain from upgrading and keep using 4.x

**Pull request merged**
