### PR TITLE
Added Ordered Checkbox

### PR DESCRIPTION
**Pull request by ChrisPhillips-cminion**
I have added a new type of prompt to allow you to order the check box list.
This extends the existing checkbox code as a new prompt and using left/right or h/l to move entries up and down. 

npm test response

---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
 lib/                |      100 |      100 |      100 |      100 |                |
  inquirer.js        |      100 |      100 |      100 |      100 |                |
 lib/objects/        |     97.1 |    95.24 |    95.45 |     97.1 |                |
  choice.js          |      100 |      100 |      100 |      100 |                |
  choices.js         |    95.83 |       75 |    94.44 |    95.83 |          18,45 |
  separator.js       |      100 |      100 |      100 |      100 |                |
 lib/prompts/        |    94.62 |     85.9 |    91.27 |    94.62 |                |
  base.js            |    95.65 |      100 |    88.24 |    95.65 |          28,64 |
  checkbox.js        |    99.12 |    89.47 |      100 |    99.12 |             28 |
  confirm.js         |    97.56 |      100 |    83.33 |    97.56 |            105 |
  editor.js          |    93.88 |    66.67 |    85.71 |    93.88 |      73,92,110 |
  expand.js          |     84.3 |       75 |       80 |     84.3 |... 180,182,254 |
  input.js           |    97.56 |      100 |    85.71 |    97.56 |            103 |
  list.js            |    94.32 |    86.21 |      100 |    94.32 |... 173,174,175 |
  orderedCheckbox.js |    97.78 |    84.78 |    95.65 |    97.78 |     28,104,126 |
  password.js        |    97.87 |      100 |     87.5 |    97.87 |            114 |
  rawlist.js         |    93.75 |       84 |       90 |    93.75 |... 143,145,148 |
 lib/ui/             |    76.92 |    63.33 |    69.23 |    76.92 |                |
  baseUI.js          |    92.59 |     87.5 |       75 |    92.59 |          31,32 |
  bottom-bar.js      |     35.9 |        0 |        0 |     35.9 |... 3,95,98,100 |
  prompt.js          |      100 |      100 |      100 |      100 |                |
 lib/utils/          |    98.25 |    94.34 |      100 |    98.25 |                |
  events.js          |      100 |      100 |      100 |      100 |                |
  paginator.js       |      100 |      100 |      100 |      100 |                |
  readline.js        |      100 |      100 |      100 |      100 |                |
  screen-manager.js  |    96.72 |    83.33 |      100 |    96.72 |         40,107 |
  utils.js           |      100 |      100 |      100 |      100 |                |
---------------------|----------|----------|----------|----------|----------------|
All files            |    93.41 |     85.8 |    90.52 |    93.41 |                |
---------------------|----------|----------|----------|----------|----------------|

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hello, thanks for sending this PR out.

I think you should publish this as a standalone plugin for Inquirer.

**Comment by ChrisPhillips-cminion** [comment]
Do you have a common method for doing plugins to inquirer or are you suggesting I just maintain my fork?

**Comment by SBoudrias** [comment]
Just like https://github.com/mokkabonna/inquirer-autocomplete-prompt

Basically what you did, but you export the prompt itself and let your end user register it.

**Comment by ChrisPhillips-cminion** [comment]
Thanks I have done this, https://www.npmjs.com/package/inquirer-orderedcheckbox

**Pull request closed without merging**
