### PR TITLE
feat(prompt): progress indicator for filter and validate with optional message

### LINKED ISSUE #631: FR: Show progress indicator on async validate
I have an async validation that takes a while. When the user presses enter, nothing seems to happen, until the validation completes. Is it possible to add some visual indication (for example, changing the question mark into a progress spinner), while the validation is running. The UI feels unresponsive now.

Unfortunately, I can't console.log something like that myself, because if the validation fails, any logging will cause the question to repeat, which is not what I want.

### PR DESCRIPTION
**Pull request by kbrandwijk**
WIP - First proposal for adding progress indicator to filter and validate step, with an optional message to be displayed during these steps. Includes an example. Will update tests and docs after initial review.

Closes #631

### CODE REVIEW

**Comment by kbrandwijk** [comment]
This functionality could in theory also be moved from `base` to `screen-manager`, so `this.screen.render` could be called with additional flags to either add a spinner to the text or the bottomText. Please let me know what you think.

**Comment by kbrandwijk** [comment]
It seems Codacy and the XO settings don't agree...

**Comment by benmonro** [comment]
any reason this can't be merged? @kbrandwijk

**Comment by SBoudrias** [comment]
@kbrandwijk I removed Codacy as its supports for eslint config is too flakey. It kept starting to mark PR as failing every few months.

I'd love to get this merged. Any chance you could resolve the conflicts and try to finalize the integration?

**Comment by sam3d** [comment]
Don't suppose you have any updates on this @kbrandwijk? This would be incredibly useful to have!

**Comment by dhensby** [comment]
This was merged via #1002 - so this can now be clsoed

**Pull request closed without merging**
