### PR TITLE
Use svg examples

### PR DESCRIPTION
**Pull request by marionebl**
* Generated with `svg-term-cli`
* Better image quality
* Smaller file sizes
* Source: https://gist.github.com/marionebl/f256ed6907a24fafe0383eee266c5fe5
* Can generate via script: https://gist.github.com/marionebl/f256ed6907a24fafe0383eee266c5fe5#file-generate-sh

### CODE REVIEW

**Comment by marionebl** [comment]
Test timeouts on Travis are unlrelated

**Comment by SBoudrias** [comment]
I love this idea, although I'd prefer to keep the assets locals to this repository so the project remains the owners of the demo images.

**Comment by marionebl** [comment]
I removed the local `*.png` files and added the `*.svg` demos. The rawgit.com urls now point to the local copies

**Comment by SBoudrias** [comment]
Looks like the white text isn't showing up on the latest demos?

**Comment by marionebl** [comment]
GitHub strips CSS when embedding SVG directly, that's the main reason why I used rawgit. Adding the prefix again should fix it.

**Comment by SBoudrias** [comment]
Thanks for the PR! I merged it aside to remove the commit I added on top.

**Pull request closed without merging**
