### PR TITLE
[WIP] Add escape key support

### PR DESCRIPTION
**Pull request by laggingreflex**
For #454. Work in progress for adding allowing escape key support (for cancelling input).

This adds some preliminary stuff. 

Lets you define `opt.onEscapeKey` function that's invoked when user presses escape key

Also allow passing a value to `opt.onEscapeKey`

```js
inquirer.prompt({
  //...
  onEscapeKey: 'some value'
  // equivalent to:
  onEscapeKey: function() { this.done('some value') }
});
```

### CODE REVIEW

**Comment by laggingreflex** [comment]
Lets you define `opt.onEscapeKey` function that's invoked when user presses escape key

```js
inquirer.prompt({
  type: 'input',
  //...
  onEscapeKey: () => { /* when user presses escape key */ }
});
```

Works for all prompt types

**Comment by laggingreflex** [comment]
Also allow passing a value to `opt.onEscapeKey`

```js
inquirer.prompt({
  //...
  onEscapeKey: 'some value'
  // equivalent to:
  onEscapeKey: function() { this.done('some value') }
});
```

**Comment by SBoudrias** [comment]
Okay, so I've been thinking about this PR and the functionality it provides. Overall, I don't think this is the right approach.

Inquirer shouldn't provide stricter APIs surface to the end user for specific use cases. I want a more generic way to allow these kind of behavior to be define by the user outside of Inquirer. Inquirer should then only provide lower level API allowing you to circumvent the current flow.

What I wish would happen is that outside of Inquirer, you set a listener for the escape key. Then inside the escape key press callback you abort the current question, maybe return to the previous prompt or use the RX api to push a different prompt in the queue - basically anything you want.

I'll close this PR as it doesn't go in a direction I'd be willing to merge. But feel free to think this issue over and send another PR reversing the control from Inquirer to the api user.

**Comment by laggingreflex** [comment]
No problem, appreciate the feedback. I did actually anticipate this might not go well with the existing code the more I began to grasp it. I'll see if I can come up with something better. 

Could you expand on this:

>outside of Inquirer, you set a listener for the escape key

Firstly, other than the "outside" aspect of it, was the `onEscapeKey` function at least close to the listener that you wanted? The user still could've done anything in there, even throw an error to abort the whole inquiry. I imagined more could've been done with `this` in it but I didn't explore much.

Or I'm guessing you don't want anything exposed that lets you use `this` of Inquirer? 

What would be the ideal thing that could be provided to the user to set a listener for the escape key? `readline` module? 

I haven't checked out the RX api in detail yet, but it seems to be an important wrapper around `readline`.

**Comment by SBoudrias** [comment]
@laggingreflex I think the user should use the readline module themselves to listen to the esc key. In pseudo code:

```js
rl.on('keypress', () => {
  inquirer.abort();
});
```

I'd explore what option there is using the RX interface in this case.

**Comment by whitecolor** [comment]
@SBoudrias It is not exactly clear how to correctly implement it with `rl.on('keypress`

I tried to insert before prompt which could be canceled and return to main menu made:
```
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    })
    rl.on('keypress', () => {
      showInitialMenu()
    });
```

But it doesn't seem to work. Can you elaborate?

**Comment by c0bra** [comment]
@whitecolor this worked for me:

**Comment by whitecolor** [comment]
Yeah I know it thanks.

**Pull request closed without merging**
