### PR TITLE
feat(confirm): add transformer feature for the new confirm prompt

### PR DESCRIPTION
**Pull request by zonemeen**
Synchronize feature with https://github.com/SBoudrias/Inquirer.js/pull/1212 in the new `confirm` prompt.

### CODE REVIEW

**Comment by zonemeen** [comment]
Hi @SBoudrias , Do you mean that the return value is still of type boolean?

**Comment by SBoudrias** [comment]
@zonemeen yes, I'd keep the return value a boolean in all cases.

**Comment by zonemeen** [comment]
Thanks for the tip, I've resubmitted the code.😄

**Review by SBoudrias — APPROVED** [review]
Thanks!

**Pull request merged**
