### PR TITLE
Added an optional question value 'helper' and 'pageHelper'

### PR DESCRIPTION
**Pull request by JezerM**
I added an optional question value for custom help message on **list type**.

### CODE REVIEW

**Comment by LitoMore** [comment]
Should document this chagne.

**Comment by abhijit-hota** [comment]
Hello. A user here.

Can you update the PR to include another list-specific option to change the end text, too?
image

Maybe an option called `listOpts` can take an object having these two parameters because we wouldn't want tot crowd the main options too much.

**Comment by JezerM** [comment]
> Hello. A user here.
> 
> Can you update the PR to include another list-specific option to change the end text, too?
> image
> 
> Maybe an option called `listOpts` can take an object having these two parameters because we wouldn't want to crowd the main options too much.

Actually, there is no specific List option to this end text, it refers to its Paginator util. Anyways, I made that change and now you could change it, check my latest commit :D

**Comment by abhijit-hota** [comment]
@JezerM That's great! Waiting for this to get reviewed.

**Comment by LitoMore** [comment]
You should think more about the documentation.

Please write the unit test for your code.

**Comment by JezerM** [comment]
> You should think more about the documentation.
> 
> 
> 
> Please write the unit test for your code.

I've never worked with testing before, but I'll try it~

**Comment by JezerM** [comment]
> You should think more about the documentation.
> 
> 
> 
> Please write the unit test for your code.

I tried to make the unit test, and went well (I guess).

**Pull request closed without merging**
