### PR TITLE
Inquirer.js Logo

### PR DESCRIPTION
**Pull request by the-simian**
I added a fancy logo that you might like. I made it in photoshop for a [blog post](http://simiansblog.com/2015/05/06/Using-Inquirer-js/#more) I was making and I wanted to give it to you if you were interested.

It looks like this

Logo

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey, thanks for that! This is awesome.

Just a few things:

- Can you make the logo smaller? Maybe float it next to the main title so it doesn't push all the content so deep into the page
- I guess your editor is removing trailing whitespace, but trailing whitespaces have a meaning in markdown and that changed the output of the readme.

**Comment by the-simian** [comment]
No sweat, I'll fix these thing today! Thank you for the feedback!

**Comment by the-simian** [comment]
Ok, I did everything you asked. 

- whitespace restored in readme
- image is smaller, and floated
- images are compressed
- image has 'padding' for readme

Pardon the number of commits, I needed to test how it appeared on github itself to be certain the readme.md looked correct. I took a couple of small attempts.

**Comment by SBoudrias** [comment]
Thanks, this is looking good! Can you squash the commits?

**Comment by the-simian** [comment]
Everything is squashed now!

**Comment by SBoudrias** [comment]
Thanks!

**Pull request merged**
