### PR TITLE
Added `prefix` and `suffix` custom option

### PR DESCRIPTION
**Pull request by Rawnly**
Added `prefix` and `suffix` options in questions objects

### CODE REVIEW

**Comment by jimthedev** [comment]
Any update on this one?

**Comment by SBoudrias** [comment]
Thanks for the PR.

Sorry it took so long to review. I wasn't totally sure this was the approach I'd like to take on the issue, but finally I think that's a fair option. I'll merge and release with next version.

**Comment by Fynnx1** [comment]
Won't `this.opt.prefix` if undefined cause 

`undefined question content`?

**Comment by SBoudrias** [comment]
@Fynnx1 we assigned default values. Are you having this issue?

**Pull request merged**
