### PR TITLE
Some documentation for RxJS

### PR DESCRIPTION
**Pull request by ev1stensberg**
I've added some documentation for RxJS. If wanted, I imagine doing more of this, as I'm doing some RxJS with Inquirer nowadays. 

Cheers!

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Seems like travis is failing on env vars. Code has no issue though

**Comment by SBoudrias** [comment]
@ev1stensberg travis failed due to the code formatting inside the example file you added not being standard with the rest of the library.

Also, could you only use lower case in file names. Ubuntu and Mac doesn't handle them the same way and it sometimes makes for really hard to find bugs.

**Comment by ev1stensberg** [comment]
Name is changed, but code style isn't as you would prefer. My editorconfig is malfunctioning, sadly, so I cannot make those changes.

**Comment by ev1stensberg** [comment]
Fixed what I could do. Is there any way to lint this with current style? Can't see any scripts in pkg.json

**Comment by ev1stensberg** [comment]
Fixed it. PR &  squash coming in shortly.

**Comment by ev1stensberg** [comment]
Ready for merge! Git skills not good enough yet to resolve conflicts without breaking the file, but working on it. Hope the PR helps you, and also great job creating this. I appreciate it.

**Pull request closed without merging**
