### PR TITLE
Add Datepicker Prompt

### PR DESCRIPTION
**Pull request by DerekTBrown**
Added a customizable datepicker component

### CODE REVIEW

**Comment by DerekTBrown** [comment]
Seems like there are some conflicting standards for style. Codacy/pr wants strings with double quotes, and the npm test command wants single quotes?

**Comment by DerekTBrown** [comment]
Right now this addition adds both the `date.js` and `dateformat` dependencies due to a usage issue in `date.js`.  I created an issue (https://github.com/datejs/Datejs/issues/104) in the hopes of resolving this, so that I can delete the `dateformat` dependency.

**Comment by DerekTBrown** [comment]
@SBoudrias I am interesting in merging this.  Can you give me an idea of what I need to do to merge / improve on?

**Comment by SBoudrias** [comment]
@DerekTBrown sorry, haven't had time to review yet.

Usually I'm not super open to add new prompts to the core. Maybe you'd like to consider publishing it as a plugin? Like https://github.com/mokkabonna/inquirer-autocomplete-prompt

**Comment by DerekTBrown** [comment]
@SBoudrias I thought about that as well, but I think this may be a pretty common need, so I thought I might shoot for package inclusion first. It is a fairly lightweight change (a single file).

**Comment by DerekTBrown** [comment]
@SBoudrias I closed in favor of creating a plugin.  I think it would be good to add a section to the Readme which includes a list of available prompt plugins.

**Comment by DerekTBrown** [comment]
https://www.npmjs.com/package/inquirer-datepicker-prompt

**Comment by SBoudrias** [comment]
@DerekTBrown I'll be happy to merge a PR adding a section about available plugins to the Readme!

**Comment by DerekTBrown** [comment]
@SBoudrias can I include gifs/screenshots of these tools, or is that too much?

**Comment by SBoudrias** [comment]
I think this can be useful, it depends how much space it takes maybe.

There's not a whole lot of plugin at the moment, so it shouldn't be too bad. Might just need to consider a proper plugin page eventually if it grows unwieldy.

**Pull request closed without merging**
