### PR TITLE
replace nullish coalescing operator with ternary

### PR DESCRIPTION
**Pull request by tys1128**
#1046

### CODE REVIEW

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
+1

**Comment by SanariSan** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/1046#issuecomment-919898281

**Review by alan-agius4 — APPROVED** [review]

**Comment by SanariSan** [comment]
@alan-agius4 this pull request replacing nullish coalescing check with just `null` check, whilst initial point was to check for `undefined` value.

Also null value can't get here, because of if statement few line above 

#1048

**Comment by alan-agius4** [comment]
`== null` also check for undefined values.

`undefined == null // true`

**Comment by SBoudrias** [comment]
Other fix was merged. Thanks for the help!

**Pull request closed without merging**
