### PR TITLE
Clears screen at bottom of prompt - alternative

### PR DESCRIPTION
**Pull request by mokkabonna**
I made some quick changes that implements it the alternative way.

And then I do in my prompt:

```js
Prompt.prototype.close = function() {
  if (this.screen.extraLinesUnderPrompt > 0) {
   utils.down(this.rl, this.screen.extraLinesUnderPrompt);
  }
}
```

This approach makes way less changes to the code. I am in favor of this.

Should also document this behaviour maybe? Nice for prompt authors to know about.

### CODE REVIEW

**Comment by SBoudrias** [comment]
This looks like the right approach to me, but we need to implement the default close behavior. I don't want prompt authors to have to write this logic themselves all the time.

**Comment by mokkabonna** [comment]
Sure

**Comment by mokkabonna** [comment]
This ok?

**Comment by SBoudrias** [comment]
Thanks!

**Comment by foisonocean** [comment]
How can i use it?

**Comment by mokkabonna** [comment]
Need to wait for it being released. That's up to @SBoudrias .

**Comment by SBoudrias** [comment]
3.0.2 is out

**Pull request merged**
