### PR TITLE
add directory type prompt for choosing a relative folder

### PR DESCRIPTION
**Pull request by nicksrandall**
I have taken the "list" type prompt and converted it to be a recurive "directory" selector. 

## Use Case
Many scoffolding tools (yeoman, plop, slush, ect.) internally rely on Inquirer as a method of getting user input before execuiting certain commands. This new prompt type will allow these tools to ask questions like "Where you would like to place this new component?" and allow their uses to select a folder (relative to a given path). 

## Limitations
Currently, this only works for selecting directories. However, it could easily be cloned to work for files.

## Issues
Testing. I need some help with the unit tests. My current test is passing but it is basically testing the file structure of this repo so that seems like a nightmare to maintain. I'm hopeing somebody has an idea on a better way to test this functionality.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey, this can be an inquirer plugin. There's no need to add it to the core.

**Comment by nicksrandall** [comment]
Ahh, looks like travis didn't like my unit tests. I agree that this could be a plugin, but I was thinking that this was a common enough use case that it could be added into core so that individual users didn't have to seperatly implement it.

**Comment by SBoudrias** [comment]
I'm planning to eventually move every prompt in the core to plugins. Yours would really fit better as a plugin.

**Comment by nicksrandall** [comment]
Ok. It was worth a try!

**Comment by Signus** [comment]
@SBoudrias, do you plan to implement a plugin guide for instances like this? I see Nick simply implemented a new Prompt prototype, which is the convention I'm following for this very same problem.

**Comment by SBoudrias** [comment]
@Signus that's the way to go currently. I eventually want to split the prompt core and the inquirer system in different modules to ease the creation of plugin. I just need more time to work on that specific feature.

I'm not sure about creating a guide right away as I feel the API is pretty sketchy and I don't want to bind people to it. - if that makes sense.

(also closing as this initial issue is resolved with a module)

**Pull request closed without merging**
