### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package chalk from 1.0.0 to 1.1.3
 Npm link :  https://www.npmjs.com/package/chalk
 Repository link : https://github.com/chalk/chalk/releases

### CODE REVIEW

**Comment by SBoudrias** [comment]
`^1.0.0` covers `^1.1.3`.

You can learn more about _Semantic Versionning_ (semver) and npm here: https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by EsrefDurna** [comment]
if you want npm will update a higher version
why don't you test it before npm distributes ? you want npm to install ^packageName but you don't want to test it with your module?

yes this is the irony of open source,
you are alright with other packages update them self and install whatever they distribute into your package,
but you also don't willing to test,

**Comment by SBoudrias** [comment]
Please take time to read the documentation I linked to you and understand how the Node community works.

No need to get mad.

**Comment by EsrefDurna** [comment]
no mad,I'm using node since day 1, please check who the person is before giving links to semver,

**Pull request closed without merging**
